name: Coto Studio - Build Hugo Site and Deploy to Linode Object Storage

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  call-reuseable-workflow:
    uses: Coto-Studio/workflows/.github/workflows/hugo-build-and-deploy.yml@main
    with:
      hugo-environment: beta
    secrets:
      obj-access-key: ${{ secrets.LINODE_ACCESS_KEY }}
      obj-secret-key: ${{ secrets.LINODE_SECRET_KEY }}
