name: Check Base Image

on:
  workflow_call:
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN:
        required: true

jobs:
  check-base-image:
    name: Check Base Image
    runs-on: ubuntu-latest
    outputs:
      rebuild: ${{ steps.baseupdatecheck.outputs.needs-updating }}
    steps:
      - name: OP Load secrets
        id: op-load-secrets
        uses: 1password/load-secrets-action@v2
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          WORKFLOWS_PAT: ${{ vars.WORKFLOWS_OP_REF }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ steps.op-load-secrets.outputs.WORKFLOWS_PAT }}

      - name: Docker Image Update Checker
        id: baseupdatecheck
        uses: lucacome/docker-image-update-checker@v2
        with:
          base-image: ${{ vars.BASE_IMAGE }}
          image: ${{ vars.IMAGE_NAME }}:${{ vars.IMAGE_TAG }} # update for your image
          platforms: linux/amd64,linux/arm64
