name: Docker

on:
  workflow_call:
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN:
        required: true

permissions:
  packages: write

jobs:
  build-and-push-image:
    name: Build & Push Image
    runs-on: ubuntu-latest
    steps:
      - name: OP Load secrets
        id: op-load-secrets
        uses: 1password/load-secrets-action@v2
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          WORKFLOWS_PAT: ${{ vars.WORKFLOWS_OP_REF }}
          DEPLOY_IMAGE: "op://${{ vars.CLIENTS_VAULT_ID }}/${{ vars.ITEM_ID }}/deploy/image"

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.op-load-secrets.outputs.WORKFLOWS_PAT }}

      - name: Get branch name
        id: branch-name
        run: echo "SHORT_REF=${GITHUB_REF#refs/*/}" >> "$GITHUB_OUTPUT"

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ steps.op-load-secrets.outputs.WORKFLOWS_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        env:
          ENVIRONMENT: ${{ steps.branch-name.outputs.SHORT_REF }}
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          # cache-from: type=registry,ref=${{ steps.op-load-secrets.outputs.DEPLOY_IMAGE }}:buildcache
          # cache-to: type=registry,ref=${{ steps.op-load-secrets.outputs.DEPLOY_IMAGE }}:buildcache,mode=max
          build-args: |
            ENVIRONMENT=${{ steps.branch-name.outputs.SHORT_REF }}
          tags: |
            ${{ steps.op-load-secrets.outputs.DEPLOY_IMAGE }}:latest
            ${{ steps.op-load-secrets.outputs.DEPLOY_IMAGE }}:${{ steps.branch-name.outputs.SHORT_REF }}
            ${{ steps.op-load-secrets.outputs.DEPLOY_IMAGE }}:${{ github.sha }}
