name: Ghost Image

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      stack-name:
        required: true
        type: string
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN:
        required: true

permissions:
  packages: write

jobs:
  build-and-push-image:
    name: Build & Push
    runs-on: ubuntu-latest
    steps:
      - name: OP Load secrets
        id: op-load-secrets
        uses: 1password/load-secrets-action@v2
        with:
          export-env: false
        env:
          WORKFLOWS_PAT: "op://Coto.Studio - Deploy/GitHub Workflows/credential"

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.op-load-secrets.outputs.WORKFLOWS_PAT }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ steps.op-load-secrets.outputs.WORKFLOWS_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ inputs.image-name}}:latest
            ${{ inputs.image-name}}:${{ github.sha }}
